name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: vascx-fork
          auto-update-conda: false
          auto-activate-base: false

      - name: Install package
        run: pip install -e .

      - name: Run tests
        run: pytest -m "not e2e and not slow"
